### ISSUE TITLE
[Template] Error in processing: "map has no entry for key 'advanced'"

### ISSUE THREAD

**Issue by stefanoghinelli** [sighupio/fury-distribution#269]
### Version
kind: OnPremises
distributionVersion: v1.27.9, v1.28.4, v1.29.4
furyctl: 0.29.8

### Description
When running furyctl to create a cluster, the following error occurs during template generation:
```
ERRO error while creating cluster: error while executing cluster creation: error while executing kubernetes phase: error while executing phase: error preparing kubernetes phase: error copying from template: error generating from template files: error applying templates: error processing template: template: hosts.yaml.tpl:81:31: executing "hosts.yaml.tpl" at <.spec.kubernetes.advanced>: map has no entry for key "advanced"
```
### Expected behavior
The template should properly handle the case where `.spec.kubernetes.advanced` doesn't exist, possibly by skipping the block or using default values.

**Comment by alessiodionisi** [comment]
Resolved from v0.29.8
