### ISSUE TITLE
Update URL in repository details

### ISSUE THREAD

**Issue by stefanoghinelli** [sighupio/fury-distribution#323]
Hi,
I noticed that the URL set in the repository details is incorrect. Currently, it is set to `kubernetesfury.com`, but it should be `docs.kubernetesfury.com`. The current URL points to an index.html page that is rendered twice, causing display issues (see [this](https://github.com/sighupio/kfd-docs/issues/129) issue).

We should consider updating the URL to fix it.

**Comment by ralgozino** [comment]
Nice catch. Fixed.

Thanks!
