### ISSUE TITLE
Bump `networking` module to `v1.12.2`

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/fury-distribution#64]
## Why?

The current version of `tigera operator` (1.28.1) does not support the ability to specify `nodeSelectors` and `tolerations` for the `csi-node-driver`. [v1.29.0](https://github.com/tigera/operator/releases) will [introduce it](https://github.com/tigera/operator/pull/2331)

## What?

On branch `feature/furyctl-next`, bump `networking` module to `v1.12.2` on kfd.yaml

Then create a patch to `templates/distribution/manifests/networking/patches/infra-nodes.yaml.tpl`

**Comment by omissis** [comment]
The version has been bumped, but the tigera operator still lacks the support for `csiNodeDriverDaemonSet` in its crd within version v3.25.0 of calico. The fix has already landed in master, so we should watch closely for the upcoming release and schedule an upgrade as soon as it gets out.
